
package SAPClasses;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZKREMENCI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZKREMENCI {


    /**
     * 
     * @param sumaTo
     * @param document
     * @param payments
     * @param dateTo
     * @param sumaFrom
     * @param office
     * @param dateFrom
     * @param customer
     */
    @WebMethod(operationName = "ZcustomerPaid")
    @RequestWrapper(localName = "ZcustomerPaid", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZcustomerPaid")
    @ResponseWrapper(localName = "ZcustomerPaidResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZcustomerPaidResponse")
    public void zcustomerPaid(
        @WebParam(name = "Customer", targetNamespace = "")
        String customer,
        @WebParam(name = "DateFrom", targetNamespace = "")
        String dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "")
        String dateTo,
        @WebParam(name = "Document", targetNamespace = "")
        String document,
        @WebParam(name = "Office", targetNamespace = "")
        String office,
        @WebParam(name = "Payments", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZbapiCustomerPayment> payments,
        @WebParam(name = "SumaFrom", targetNamespace = "")
        BigDecimal sumaFrom,
        @WebParam(name = "SumaTo", targetNamespace = "")
        BigDecimal sumaTo);

    /**
     * 
     * @param checkCommunities
     * @param lastnameM
     * @param orgUnit
     * @param outTab
     * @param fstnameM
     * @param employeeId
     * @param job
     * @param orgtxt
     * @param jobtxt
     */
    @WebMethod(operationName = "ZsearchPerson")
    @RequestWrapper(localName = "ZsearchPerson", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsearchPerson")
    @ResponseWrapper(localName = "ZsearchPersonResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsearchPersonResponse")
    public void zsearchPerson(
        @WebParam(name = "CheckCommunities", targetNamespace = "")
        String checkCommunities,
        @WebParam(name = "EmployeeId", targetNamespace = "")
        String employeeId,
        @WebParam(name = "FstnameM", targetNamespace = "")
        String fstnameM,
        @WebParam(name = "Job", targetNamespace = "")
        String job,
        @WebParam(name = "Jobtxt", targetNamespace = "")
        String jobtxt,
        @WebParam(name = "LastnameM", targetNamespace = "")
        String lastnameM,
        @WebParam(name = "OrgUnit", targetNamespace = "")
        String orgUnit,
        @WebParam(name = "Orgtxt", targetNamespace = "")
        String orgtxt,
        @WebParam(name = "OutTab", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZpernDebitor> outTab);

    /**
     * 
     * @param messtab
     * @param subrc
     * @param billNum
     * @param billNumber
     * @param cBillNumber
     */
    @WebMethod(operationName = "ZsdBillCancel")
    @RequestWrapper(localName = "ZsdBillCancel", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillCancel")
    @ResponseWrapper(localName = "ZsdBillCancelResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillCancelResponse")
    public void zsdBillCancel(
        @WebParam(name = "BillNum", targetNamespace = "")
        String billNum,
        @WebParam(name = "Messtab", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "BillNumber", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> billNumber,
        @WebParam(name = "CBillNumber", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> cBillNumber,
        @WebParam(name = "Subrc", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> subrc);

    /**
     * 
     * @param person
     * @param name
     * @param customers
     * @param customer
     */
    @WebMethod(operationName = "ZdebitorSearch")
    @RequestWrapper(localName = "ZdebitorSearch", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZdebitorSearch")
    @ResponseWrapper(localName = "ZdebitorSearchResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZdebitorSearchResponse")
    public void zdebitorSearch(
        @WebParam(name = "Customer", targetNamespace = "")
        String customer,
        @WebParam(name = "Customers", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZdebitorkrem> customers,
        @WebParam(name = "Name", targetNamespace = "")
        String name,
        @WebParam(name = "Person", targetNamespace = "")
        String person);

    /**
     * 
     * @param spoolid
     * @param pdfBinaryData
     * @param billNumber
     */
    @WebMethod(operationName = "ZsdBillPrint")
    @RequestWrapper(localName = "ZsdBillPrint", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillPrint")
    @ResponseWrapper(localName = "ZsdBillPrintResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillPrintResponse")
    public void zsdBillPrint(
        @WebParam(name = "BillNumber", targetNamespace = "")
        String billNumber,
        @WebParam(name = "PdfBinaryData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<byte[]> pdfBinaryData,
        @WebParam(name = "Spoolid", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> spoolid);

    /**
     * 
     * @param messtab
     * @param orderNum
     * @param subrc
     * @param billNumber
     */
    @WebMethod(operationName = "ZsdBillCreate")
    @RequestWrapper(localName = "ZsdBillCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillCreate")
    @ResponseWrapper(localName = "ZsdBillCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdBillCreateResponse")
    public void zsdBillCreate(
        @WebParam(name = "Messtab", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderNum", targetNamespace = "")
        String orderNum,
        @WebParam(name = "BillNumber", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> billNumber,
        @WebParam(name = "Subrc", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> subrc);

    /**
     * 
     * @param orderType
     * @param messtab
     * @param orderClient
     * @param subrc
     * @param orderDoc
     * @param salesOrder
     */
    @WebMethod(operationName = "ZsdOrderCreate")
    @RequestWrapper(localName = "ZsdOrderCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdOrderCreate")
    @ResponseWrapper(localName = "ZsdOrderCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdOrderCreateResponse")
    public void zsdOrderCreate(
        @WebParam(name = "Messtab", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderClient", targetNamespace = "")
        String orderClient,
        @WebParam(name = "OrderDoc", targetNamespace = "")
        String orderDoc,
        @WebParam(name = "OrderType", targetNamespace = "")
        String orderType,
        @WebParam(name = "SalesOrder", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> salesOrder,
        @WebParam(name = "Subrc", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> subrc);

    /**
     * 
     * @param itemNum
     * @param itemCnt
     * @param orderItem
     * @param messtab
     * @param orderNum
     * @param itemDate
     * @param subrc
     * @param itemSapPrice
     * @param salesOrder
     * @param itemText
     */
    @WebMethod(operationName = "ZsdOrderAddPos")
    @RequestWrapper(localName = "ZsdOrderAddPos", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdOrderAddPos")
    @ResponseWrapper(localName = "ZsdOrderAddPosResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdOrderAddPosResponse")
    public void zsdOrderAddPos(
        @WebParam(name = "ItemCnt", targetNamespace = "")
        String itemCnt,
        @WebParam(name = "ItemNum", targetNamespace = "")
        String itemNum,
        @WebParam(name = "ItemText", targetNamespace = "")
        String itemText,
        @WebParam(name = "Messtab", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderNum", targetNamespace = "")
        String orderNum,
        @WebParam(name = "ItemDate", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> itemDate,
        @WebParam(name = "ItemSapPrice", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BigDecimal> itemSapPrice,
        @WebParam(name = "OrderItem", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> orderItem,
        @WebParam(name = "SalesOrder", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> salesOrder,
        @WebParam(name = "Subrc", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> subrc);

    /**
     * 
     * @param matnr
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "ZgetPriceByMatnr")
    @WebResult(name = "Kbetr", targetNamespace = "")
    @RequestWrapper(localName = "ZgetPriceByMatnr", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZgetPriceByMatnr")
    @ResponseWrapper(localName = "ZgetPriceByMatnrResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZgetPriceByMatnrResponse")
    public BigDecimal zgetPriceByMatnr(
        @WebParam(name = "Matnr", targetNamespace = "")
        String matnr);

    /**
     * 
     * @param zmatnrtable
     */
    @WebMethod(operationName = "ZsdGetMatnrForSmit")
    @RequestWrapper(localName = "ZsdGetMatnrForSmit", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdGetMatnrForSmit")
    @ResponseWrapper(localName = "ZsdGetMatnrForSmitResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "SAPClasses.ZsdGetMatnrForSmitResponse")
    public void zsdGetMatnrForSmit(
        @WebParam(name = "Zmatnrtable", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZsdsmitmatnr> zmatnrtable);

}
