
package SAPClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZKREMENCI", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/D:/work/workdirectory/TransportService/src/main/resources/sap.wsdl")
public class ZKREMENCI_Service
    extends Service
{

    private final static URL ZKREMENCI_WSDL_LOCATION;
    private final static WebServiceException ZKREMENCI_EXCEPTION;
    private final static QName ZKREMENCI_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZKREMENCI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/work/workdirectory/TransportService/src/main/resources/sap.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZKREMENCI_WSDL_LOCATION = url;
        ZKREMENCI_EXCEPTION = e;
    }

    public ZKREMENCI_Service() {
        super(__getWsdlLocation(), ZKREMENCI_QNAME);
    }

    public ZKREMENCI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZKREMENCI_QNAME, features);
    }

    public ZKREMENCI_Service(URL wsdlLocation) {
        super(wsdlLocation, ZKREMENCI_QNAME);
    }

    public ZKREMENCI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZKREMENCI_QNAME, features);
    }

    public ZKREMENCI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZKREMENCI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZKREMENCI
     */
    @WebEndpoint(name = "ZKREMENCI")
    public ZKREMENCI getZKREMENCI() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZKREMENCI"), ZKREMENCI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZKREMENCI
     */
    @WebEndpoint(name = "ZKREMENCI")
    public ZKREMENCI getZKREMENCI(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZKREMENCI"), ZKREMENCI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZKREMENCI_EXCEPTION!= null) {
            throw ZKREMENCI_EXCEPTION;
        }
        return ZKREMENCI_WSDL_LOCATION;
    }

}
