package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-09T13:21:46.310+02:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "zkreminci")
@XmlSeeAlso({ObjectFactory.class})
public interface Zkreminci {

    @WebMethod(operationName = "ZsdBillPrint")
    @RequestWrapper(localName = "ZsdBillPrint", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillPrint")
    @ResponseWrapper(localName = "ZsdBillPrintResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillPrintResponse")
    public void zsdBillPrint(
        @WebParam(name = "BillNumber", targetNamespace = "")
        java.lang.String billNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "PdfBinaryData", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfBinaryData,
        @WebParam(mode = WebParam.Mode.OUT, name = "Spoolid", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> spoolid
    );

    @WebMethod(operationName = "ZsdOrderAddPos")
    @RequestWrapper(localName = "ZsdOrderAddPos", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdOrderAddPos")
    @ResponseWrapper(localName = "ZsdOrderAddPosResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdOrderAddPosResponse")
    public void zsdOrderAddPos(
        @WebParam(name = "ItemCnt", targetNamespace = "")
        java.lang.String itemCnt,
        @WebParam(name = "ItemNum", targetNamespace = "")
        java.lang.String itemNum,
        @WebParam(name = "ItemText", targetNamespace = "")
        java.lang.String itemText,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Messtab", targetNamespace = "")
        javax.xml.ws.Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderNum", targetNamespace = "")
        java.lang.String orderNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "ItemDate", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> itemDate,
        @WebParam(mode = WebParam.Mode.OUT, name = "ItemSapPrice", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> itemSapPrice,
        @WebParam(mode = WebParam.Mode.OUT, name = "OrderItem", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> orderItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "SalesOrder", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> salesOrder,
        @WebParam(mode = WebParam.Mode.OUT, name = "Subrc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> subrc
    );

    @WebMethod(operationName = "ZsdBillCreate")
    @RequestWrapper(localName = "ZsdBillCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillCreate")
    @ResponseWrapper(localName = "ZsdBillCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillCreateResponse")
    public void zsdBillCreate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Messtab", targetNamespace = "")
        javax.xml.ws.Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderNum", targetNamespace = "")
        java.lang.String orderNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "BillNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> billNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "Subrc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> subrc
    );

    @WebMethod(operationName = "ZsdGetMatnrForSmit")
    @RequestWrapper(localName = "ZsdGetMatnrForSmit", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdGetMatnrForSmit")
    @ResponseWrapper(localName = "ZsdGetMatnrForSmitResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdGetMatnrForSmitResponse")
    public void zsdGetMatnrForSmit(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Zmatnrtable", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZsdsmitmatnr> zmatnrtable
    );

    @WebMethod(operationName = "ZgetPriceByMatnr")
    @RequestWrapper(localName = "ZgetPriceByMatnr", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZgetPriceByMatnr")
    @ResponseWrapper(localName = "ZgetPriceByMatnrResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZgetPriceByMatnrResponse")
    @WebResult(name = "Kbetr", targetNamespace = "")
    public java.math.BigDecimal zgetPriceByMatnr(
        @WebParam(name = "Matnr", targetNamespace = "")
        java.lang.String matnr
    );

    @WebMethod(operationName = "ZdebitorSearch")
    @RequestWrapper(localName = "ZdebitorSearch", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZdebitorSearch")
    @ResponseWrapper(localName = "ZdebitorSearchResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZdebitorSearchResponse")
    public void zdebitorSearch(
        @WebParam(name = "Customer", targetNamespace = "")
        java.lang.String customer,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Customers", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZdebitorkrem> customers,
        @WebParam(name = "Name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "Person", targetNamespace = "")
        java.lang.String person
    );

    @WebMethod(operationName = "ZsdBillCancel")
    @RequestWrapper(localName = "ZsdBillCancel", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillCancel")
    @ResponseWrapper(localName = "ZsdBillCancelResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdBillCancelResponse")
    public void zsdBillCancel(
        @WebParam(name = "BillNum", targetNamespace = "")
        java.lang.String billNum,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Messtab", targetNamespace = "")
        javax.xml.ws.Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(mode = WebParam.Mode.OUT, name = "BillNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> billNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "CBillNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> cBillNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "Subrc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> subrc
    );

    @WebMethod(operationName = "ZcustomerPaid")
    @RequestWrapper(localName = "ZcustomerPaid", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcustomerPaid")
    @ResponseWrapper(localName = "ZcustomerPaidResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZcustomerPaidResponse")
    public void zcustomerPaid(
        @WebParam(name = "Customer", targetNamespace = "")
        java.lang.String customer,
        @WebParam(name = "DateFrom", targetNamespace = "")
        java.lang.String dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "")
        java.lang.String dateTo,
        @WebParam(name = "Document", targetNamespace = "")
        java.lang.String document,
        @WebParam(name = "Office", targetNamespace = "")
        java.lang.String office,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Payments", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZbapiCustomerPayment> payments,
        @WebParam(name = "SumaFrom", targetNamespace = "")
        java.math.BigDecimal sumaFrom,
        @WebParam(name = "SumaTo", targetNamespace = "")
        java.math.BigDecimal sumaTo
    );

    @WebMethod(operationName = "ZsdOrderCreate")
    @RequestWrapper(localName = "ZsdOrderCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdOrderCreate")
    @ResponseWrapper(localName = "ZsdOrderCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdOrderCreateResponse")
    public void zsdOrderCreate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Messtab", targetNamespace = "")
        javax.xml.ws.Holder<TableOfBdcmsgcoll> messtab,
        @WebParam(name = "OrderClient", targetNamespace = "")
        java.lang.String orderClient,
        @WebParam(name = "OrderType", targetNamespace = "")
        java.lang.String orderType,
        @WebParam(mode = WebParam.Mode.OUT, name = "SalesOrder", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> salesOrder,
        @WebParam(mode = WebParam.Mode.OUT, name = "Subrc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> subrc
    );

    @WebMethod(operationName = "ZsearchPerson")
    @RequestWrapper(localName = "ZsearchPerson", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsearchPerson")
    @ResponseWrapper(localName = "ZsearchPersonResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsearchPersonResponse")
    public void zsearchPerson(
        @WebParam(name = "CheckCommunities", targetNamespace = "")
        java.lang.String checkCommunities,
        @WebParam(name = "EmployeeId", targetNamespace = "")
        java.lang.String employeeId,
        @WebParam(name = "FstnameM", targetNamespace = "")
        java.lang.String fstnameM,
        @WebParam(name = "Job", targetNamespace = "")
        java.lang.String job,
        @WebParam(name = "Jobtxt", targetNamespace = "")
        java.lang.String jobtxt,
        @WebParam(name = "LastnameM", targetNamespace = "")
        java.lang.String lastnameM,
        @WebParam(name = "OrgUnit", targetNamespace = "")
        java.lang.String orgUnit,
        @WebParam(name = "Orgtxt", targetNamespace = "")
        java.lang.String orgtxt,
        @WebParam(mode = WebParam.Mode.INOUT, name = "OutTab", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZpernDebitor> outTab
    );
}
