package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-09T13:21:46.580+02:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "ZKREMINCI", 
                  wsdlLocation = "file:/C:/Users/us9047/Desktop/TransportService/TransportService/src/main/resources/sap.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZKREMINCI_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZKREMINCI");
    public final static QName ZKREMINCI = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZKREMINCI");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/us9047/Desktop/TransportService/TransportService/src/main/resources/sap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZKREMINCI_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/us9047/Desktop/TransportService/TransportService/src/main/resources/sap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZKREMINCI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZKREMINCI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZKREMINCI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZKREMINCI_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZKREMINCI_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZKREMINCI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Zkreminci
     */
    @WebEndpoint(name = "ZKREMINCI")
    public Zkreminci getZKREMINCI() {
        return super.getPort(ZKREMINCI, Zkreminci.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Zkreminci
     */
    @WebEndpoint(name = "ZKREMINCI")
    public Zkreminci getZKREMINCI(WebServiceFeature... features) {
        return super.getPort(ZKREMINCI, Zkreminci.class, features);
    }

}
